### ISSUE TITLE
New PyPI release?

### ISSUE THREAD

**Issue by Swindle98** [dalya/Sequencer#7]
Hi, I kept getting repeated errors from deprecated functions that seemed to have been patched in this repository, It was only today that I thought to check the last time the pypi repository was updated (2020) and the last commit here was 6months ago... 

Ive installed this repo and installed from there. It's now functioning perfectly fine...

Could the either the PyPI repository be updated, or the readme be updated to reccomend isntalling from this repository?

Happy to do a PR to add the steps to the readme if thats what you choose.

**Comment by dalya** [comment]
Thanks @Swindle98 for your note. The repo was indeed updated but I haven't had time to deal with the PyPI update. I will update the README file as you suggested. Thanks!!
